'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, ChevronDown, Heart, Menu, Minus, Plus, Search, ShoppingBag, SlidersHorizontal, UserRound, X } from 'lucide-react';
import { money, type Locale } from '@dara/shared';
import { API, api, csrf, mutate, previewProducts, type CartLine, type Product, type Variant } from './data';
import Admin from './admin/Admin';

const copy = {
  en: { shipping: 'Complimentary Kuwait delivery on orders over 50 KWD', explore: 'Explore the collection', shop: 'Shop all', journal: 'The Dara Edit', story: 'Our story', search: 'Search', favorites: 'Saved pieces', bag: 'Bag', account: 'Account', heroEyebrow: 'THE ART OF BEING HOME', heroTitle: 'A softer way<br/>to live.', heroText: 'Considered pieces for the rooms we return to, the rituals we repeat, and the moments in between.', discover: 'Discover the collection', signature: 'DARA SIGNATURES', favouritesTitle: 'The pieces you come home to.', viewAll: 'View all pieces', categories: 'EXPLORE BY ROOM', categoriesTitle: 'Find your kind of comfort.', ctaEyebrow: 'MADE FOR THE EVERYDAY', ctaTitle: 'A home is never finished. It simply becomes more yours.', ctaText: 'Beautifully useful objects, chosen for how they feel and how they last.', ctaButton: 'Read our story', newsletter: 'Notes from Dara', newsletterText: 'New collections, quiet inspiration, and thoughtful offers.', subscribe: 'Subscribe', email: 'Email address', add: 'Add to bag', added: 'Added to bag', details: 'The details', delivery: 'Delivery across Kuwait in 2–4 days.', returns: 'Easy returns within 14 days.', filter: 'Filter', sort: 'Sort by', noResults: 'No pieces found', noResultsText: 'Try another search or explore all pieces.', all: 'All pieces', priceLow: 'Price: low to high', priceHigh: 'Price: high to low', cartTitle: 'Your bag', emptyCart: 'Your bag is waiting.', emptyCartText: 'Find something that feels like home.', continue: 'Continue shopping', subtotal: 'Subtotal', deliveryLabel: 'Delivery', total: 'Total', checkout: 'Continue to checkout', free: 'Complimentary', quantity: 'Quantity', remove: 'Remove', checkoutTitle: 'Checkout', contact: 'Contact & delivery', fullName: 'Full name', phone: 'Phone number', address: 'Delivery address', promo: 'Promotion code', apply: 'Apply', placeOrder: 'Place simulated order', paymentNote: 'Demo checkout · No card will be charged.', orderPlaced: 'Your order is placed.', orderThanks: 'Thank you for making room for Dara.', orderNumber: 'Order number', track: 'Track your order', signIn: 'Sign in', register: 'Create account', password: 'Password', myOrders: 'My orders', savedTitle: 'Your saved pieces', emptySaved: 'A little space for what you love.', dashboard: 'Dashboard', loading: 'Gathering the details…', error: 'Something went wrong. Please try again.', preview: 'Preview catalog shown. Start the API and database to shop.' },
  ar: { shipping: 'توصيل مجاني داخل الكويت للطلبات فوق ٥٠ د.ك', explore: 'اكتشف المجموعة', shop: 'تسوق الكل', journal: 'مختارات دارا', story: 'قصتنا', search: 'بحث', favorites: 'المفضلة', bag: 'الحقيبة', account: 'حسابي', heroEyebrow: 'فن العيش في البيت', heroTitle: 'لحياة أكثر<br/>سكينة.', heroText: 'قطع منتقاة للغرف التي نعود إليها، والطقوس التي نكررها، وللحظات بينهما.', discover: 'اكتشف المجموعة', signature: 'مختارات دارا', favouritesTitle: 'قطع تحب العودة إليها.', viewAll: 'عرض كل القطع', categories: 'تسوق حسب المساحة', categoriesTitle: 'اكتشف راحتك الخاصة.', ctaEyebrow: 'صنعت لكل يوم', ctaTitle: 'المنزل لا يكتمل أبداً. بل يصبح أقرب إليك.', ctaText: 'قطع تجمع الجمال والفائدة، اخترناها لإحساسها ومتانتها.', ctaButton: 'اقرأ قصتنا', newsletter: 'رسائل من دارا', newsletterText: 'مجموعات جديدة، وإلهام هادئ، وعروض مختارة.', subscribe: 'اشترك', email: 'البريد الإلكتروني', add: 'أضف إلى الحقيبة', added: 'أضيفت إلى الحقيبة', details: 'التفاصيل', delivery: 'توصيل إلى جميع أنحاء الكويت خلال ٢–٤ أيام.', returns: 'إرجاع سهل خلال ١٤ يوماً.', filter: 'تصفية', sort: 'الترتيب', noResults: 'لم نجد قطعاً', noResultsText: 'جرّب بحثاً آخر أو تصفح جميع القطع.', all: 'كل القطع', priceLow: 'السعر: من الأقل', priceHigh: 'السعر: من الأعلى', cartTitle: 'حقيبتك', emptyCart: 'حقيبتك تنتظر.', emptyCartText: 'اعثر على ما يشبه بيتك.', continue: 'تابع التسوق', subtotal: 'المجموع الفرعي', deliveryLabel: 'التوصيل', total: 'الإجمالي', checkout: 'إتمام الطلب', free: 'مجاني', quantity: 'الكمية', remove: 'إزالة', checkoutTitle: 'إتمام الطلب', contact: 'بيانات التواصل والتوصيل', fullName: 'الاسم الكامل', phone: 'رقم الهاتف', address: 'عنوان التوصيل', promo: 'رمز الخصم', apply: 'تطبيق', placeOrder: 'تأكيد الطلب التجريبي', paymentNote: 'طلب تجريبي · لن يتم خصم أي مبلغ.', orderPlaced: 'تم تأكيد طلبك.', orderThanks: 'شكراً لإفساح مكان لدارا.', orderNumber: 'رقم الطلب', track: 'تتبع طلبك', signIn: 'تسجيل الدخول', register: 'إنشاء حساب', password: 'كلمة المرور', myOrders: 'طلباتي', savedTitle: 'قطعك المفضلة', emptySaved: 'مساحة صغيرة لما تحب.', dashboard: 'لوحة التحكم', loading: 'نجمع التفاصيل…', error: 'حدث خطأ. حاول مجدداً.', preview: 'كتالوج للمعاينة. شغّل الواجهة البرمجية وقاعدة البيانات للتسوق.' }
} as const;
const categoryNames: Record<string, [string, string]> = { living: ['Living', 'المعيشة'], lighting: ['Lighting', 'الإضاءة'], tableware: ['Tableware', 'المائدة'], textiles: ['Textiles', 'المنسوجات'], decor: ['Objects & décor', 'القطع والديكور'] };
const categoryPictures: Record<string, string> = { living: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&q=80', lighting: 'https://images.unsplash.com/photo-1543198126-a8ad8e47fb22?w=800&q=80', tableware: 'https://images.unsplash.com/photo-1490312278390-ab64016e0aa9?w=800&q=80', textiles: 'https://images.unsplash.com/photo-1618220179428-22790b461013?w=800&q=80', decor: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=800&q=80' };
const readCart = (): CartLine[] => { try { return JSON.parse(localStorage.getItem('dara-cart') ?? '[]'); } catch { return []; } };
const readSaved = (): string[] => { try { return JSON.parse(localStorage.getItem('dara-saved') ?? '[]'); } catch { return []; } };

export default function DaraApp({ locale, path }: { locale: Locale; path: string[] }) {
  const t = copy[locale]; const ar = locale === 'ar'; const base = `/${locale}`;
  const [cart, setCart] = useState<CartLine[]>([]); const [saved, setSaved] = useState<string[]>([]);
  const [products, setProducts] = useState<Product[]>(previewProducts); const [product, setProduct] = useState<Product | null>(null);
  const [apiReady, setApiReady] = useState(true); const [loading, setLoading] = useState(true); const [menuOpen, setMenuOpen] = useState(false); const [searchOpen, setSearchOpen] = useState(false);
  const [search, setSearch] = useState(''); const [category, setCategory] = useState('all'); const [collection, setCollection] = useState('all'); const [sort, setSort] = useState('featured'); const [selectedVariant, setSelectedVariant] = useState('');
  const [notice, setNotice] = useState(''); const [quote, setQuote] = useState<{ subtotalFils: number; discountFils: number; deliveryFils: number; totalFils: number } | null>(null); const [promoCode, setPromoCode] = useState('');
  const [form, setForm] = useState({ name: '', email: '', phone: '', address: '' }); const [submitting, setSubmitting] = useState(false); const [order, setOrder] = useState<any>(null); const [accountMode, setAccountMode] = useState<'login'|'register'>('login'); const [password, setPassword] = useState(''); const [session, setSession] = useState<any>(null); const [orders, setOrders] = useState<any[]>([]);
  const section = path[0] ?? 'home'; const productSlug = path[1];
  const direction = ar ? 'rtl' : 'ltr'; const arrow = ar ? <ArrowLeft size={17} /> : <ArrowRight size={17} />;
  const name = (p: Product) => ar ? p.nameAr : p.nameEn;
  const variantName = (v: Variant) => ar ? v.labelAr : v.labelEn;
  const hrefLocale = ar ? `/en/${path.join('/')}` : `/ar/${path.join('/')}`;
  useEffect(() => { document.documentElement.lang = locale; document.documentElement.dir = direction; setCart(readCart()); setSaved(readSaved()); api('/v1/auth/session').then(setSession).catch(() => {}); }, [locale, direction]);
  useEffect(() => { if (section === 'shop') { const params = new URLSearchParams(window.location.search); setCategory(params.get('category') ?? 'all'); setCollection(params.get('collection') ?? 'all'); setSearch(params.get('q') ?? ''); } }, [section]);
  useEffect(() => {
    const qs = new URLSearchParams(); if (section === 'shop' && category !== 'all') qs.set('category', category); if (section === 'shop' && collection !== 'all') qs.set('collection', collection); if (section === 'shop' && search) qs.set('q', search); if (section === 'shop' && sort !== 'featured') qs.set('sort', sort);
    setLoading(true);
    api<{ items: Product[] }>(`/v1/catalog/products?${qs}`).then(data => { setProducts(data.items); setApiReady(true); }).catch(() => { setProducts(previewProducts); setApiReady(false); }).finally(() => setLoading(false));
  }, [section, category, collection, sort, search]);
  useEffect(() => { if (section === 'product' && productSlug) { setLoading(true); api<Product>(`/v1/catalog/products/${productSlug}`).then(p => { setProduct(p); setSelectedVariant(p.variants?.find(v => v.stock > 0)?.id ?? p.variants?.[0]?.id ?? ''); }).catch(() => { const p = previewProducts.find(x => x.slug === productSlug) ?? null; setProduct(p); setApiReady(false); }).finally(() => setLoading(false)); } }, [section, productSlug]);
  useEffect(() => { if (section === 'order' && productSlug) api(`/v1/orders/${productSlug}?token=${encodeURIComponent(new URLSearchParams(window.location.search).get('token') ?? '')}`).then(setOrder).catch(() => setOrder(null)); }, [section, productSlug]);
  useEffect(() => { if (section === 'account' && session?.user) api<any[]>('/v1/orders').then(setOrders).catch(() => {}); }, [section, session]);
  useEffect(() => { if (!cart.length) { setQuote(null); return; } api<any>('/v1/cart/quote', { method: 'POST', body: JSON.stringify({ items: cart.map(x => ({ variantId: x.variant.id, quantity: x.quantity })), promotionCode: promoCode || undefined }) }).then(setQuote).catch(() => setQuote(null)); }, [cart, promoCode]);
  useEffect(() => { if (!apiReady || !['product', 'cart', 'checkout'].includes(section) || typeof EventSource === 'undefined') return; const source = new EventSource(`${API}/v1/events/inventory`, { withCredentials: true }); source.addEventListener('inventory', (event: MessageEvent) => { const data = JSON.parse(event.data); setCart(current => current.map(line => line.variant.id === data.variantId ? { ...line, variant: { ...line.variant, stock: data.stock } } : line)); setProduct(current => current ? { ...current, variants: current.variants?.map(v => v.id === data.variantId ? { ...v, stock: data.stock } : v) } : current); }); return () => source.close(); }, [apiReady, section]);
  const updateCart = useCallback((next: CartLine[]) => { setCart(next); localStorage.setItem('dara-cart', JSON.stringify(next)); }, []);
  const toggleSaved = (slug: string) => { const next = saved.includes(slug) ? saved.filter(s => s !== slug) : [...saved, slug]; setSaved(next); localStorage.setItem('dara-saved', JSON.stringify(next)); };
  const addToCart = () => { if (!product) return; const variant = product.variants?.find(v => v.id === selectedVariant); if (!variant) { setNotice(t.preview); return; } const current = cart.find(x => x.variant.id === variant.id); updateCart(current ? cart.map(x => x.variant.id === variant.id ? { ...x, quantity: Math.min(variant.stock, x.quantity + 1) } : x) : [...cart, { product, variant, quantity: 1 }]); setNotice(t.added); setTimeout(() => setNotice(''), 3500); };
  const cartCount = cart.reduce((sum, line) => sum + line.quantity, 0);
  const subtotal = cart.reduce((sum, line) => sum + line.variant.priceFils * line.quantity, 0);
  const displayProducts = section === 'favorites' ? products.filter(p => saved.includes(p.slug)) : products;
  const signatureProducts = ['safa-lounge-chair', 'masa-table-lamp', 'dara-clay-vessel', 'linen-story-throw'].map(slug => products.find(p => p.slug === slug)).filter((p): p is Product => Boolean(p));
  const primaryNav = <><a href={`${base}/shop`}>{t.shop}</a><a href={`${base}/shop?category=living`}>{ar ? 'غرفة المعيشة' : 'Living'}</a><a href={`${base}/shop?category=lighting`}>{ar ? 'الإضاءة' : 'Lighting'}</a><a href={`${base}/shop?category=tableware`}>{ar ? 'المائدة' : 'Tableware'}</a><a href={`${base}/story`}>{t.story}</a></>;
  const productCard = (p: Product, index: number) => <article className="product-card" key={p.id}><div className="product-media"><a href={`${base}/product/${p.slug}`} aria-label={name(p)}><img src={p.imageUrl} alt={name(p)} loading={index < 4 ? 'eager' : 'lazy'} /></a>{p.featured && <span className="product-tag">{ar ? 'مختارات دارا' : 'DARA PICK'}</span>}<button className={`save-button ${saved.includes(p.slug) ? 'is-saved' : ''}`} aria-label={saved.includes(p.slug) ? `${t.remove} ${name(p)}` : `${t.favorites}: ${name(p)}`} onClick={() => toggleSaved(p.slug)}><Heart size={19} fill={saved.includes(p.slug) ? 'currentColor' : 'none'} /></button></div><div className="product-info"><div><span className="product-category">{categoryNames[p.category ?? 'decor']?.[ar ? 1 : 0]}</span><a href={`${base}/product/${p.slug}`}><h3>{name(p)}</h3></a></div><span>{money(p.minPriceFils, locale)}</span></div></article>;
  const empty = (title: string, description: string) => <div className="empty-state"><span className="empty-symbol">✳</span><h2>{title}</h2><p>{description}</p><a className="button dark" href={`${base}/shop`}>{t.continue} {arrow}</a></div>;
  const submitOrder = async (e: React.FormEvent) => { e.preventDefault(); if (!cart.length) return; setSubmitting(true); setNotice(''); try { const data = await mutate<{ order: { id: string }; trackingToken?: string }>('/v1/checkout', 'POST', { ...form, items: cart.map(x => ({ variantId: x.variant.id, quantity: x.quantity })), promotionCode: promoCode || undefined, idempotencyKey: sessionStorage.getItem('dara-checkout-key') ?? (() => { const key = crypto.randomUUID(); sessionStorage.setItem('dara-checkout-key', key); return key; })() }); updateCart([]); sessionStorage.removeItem('dara-checkout-key'); window.location.href = `${base}/order/${data.order.id}?token=${encodeURIComponent(data.trackingToken ?? '')}`; } catch (error: any) { setNotice(error.message); } finally { setSubmitting(false); } };
  const submitAuth = async (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); setSubmitting(true); setNotice(''); const data = Object.fromEntries(new FormData(e.currentTarget)); try { const result = await mutate<any>(`/v1/auth/${accountMode}`, 'POST', data); setSession(result); setPassword(''); } catch (error: any) { setNotice(error.message); } finally { setSubmitting(false); } };
  const navFooter = <><div><h4>DARA</h4><p>{ar ? 'قطع مدروسة لبيت يشبهك.' : 'Considered objects for a life well lived.'}</p></div><div><h5>{ar ? 'تسوق' : 'Shop'}</h5><a href={`${base}/shop`}>{t.shop}</a><a href={`${base}/shop?category=living`}>{categoryNames.living[ar ? 1 : 0]}</a><a href={`${base}/shop?category=decor`}>{categoryNames.decor[ar ? 1 : 0]}</a></div><div><h5>{ar ? 'دارا' : 'Dara'}</h5><a href={`${base}/story`}>{t.story}</a><a href={`${base}/account`}>{t.account}</a><a href={`${base}/admin`}>{t.dashboard}</a></div><div className="footer-news"><h5>{t.newsletter}</h5><p>{t.newsletterText}</p><form onSubmit={e => { e.preventDefault(); setNotice(ar ? 'شكراً لاشتراكك.' : 'Thank you for joining us.'); }}><input type="email" required placeholder={t.email} aria-label={t.email}/><button aria-label={t.subscribe}>{arrow}</button></form></div></>;
  if (section === 'admin') return <Admin locale={locale} />;
  return <div className="site" dir={direction}>
    <div className="announcement">{t.shipping}<span>✳</span></div>
    <header className="site-header"><div className="header-inner"><button className="icon-button mobile-menu" aria-label="Open menu" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button><a href={base} className="brand" aria-label="Dara home"><span className="brand-mark">✳</span><span>DARA</span><small>دارا</small></a><nav className={`main-nav ${menuOpen ? 'open' : ''}`} aria-label="Main navigation">{primaryNav}</nav><div className="header-actions"><button className="icon-button search-trigger" aria-label={t.search} onClick={() => setSearchOpen(!searchOpen)}><Search size={21}/></button><a className="icon-button desktop-icon" href={`${base}/favorites`} aria-label={t.favorites}><Heart size={20}/></a><a className="icon-button desktop-icon" href={`${base}/account`} aria-label={t.account}><UserRound size={20}/></a><a className="bag-link" href={`${base}/cart`} aria-label={`${t.bag}, ${cartCount}`}><ShoppingBag size={20}/><span>{cartCount}</span></a><a className="locale-switch" href={hrefLocale} lang={ar ? 'en' : 'ar'}>{ar ? 'EN' : 'العربية'}</a></div></div>{searchOpen && <form className="search-panel" onSubmit={e => { e.preventDefault(); window.location.href = `${base}/shop?q=${encodeURIComponent(search)}`; }}><Search size={22}/><input autoFocus placeholder={ar ? 'ابحث عن قطعة...' : 'Search for something beautiful...'} value={search} onChange={e => setSearch(e.target.value)}/><button className="text-button" type="submit">{t.search} {arrow}</button><button className="icon-button" type="button" aria-label="Close search" onClick={() => setSearchOpen(false)}><X/></button></form>}</header>
    {notice && <div className="toast" role="status"><Check size={17}/>{notice}<button aria-label="Dismiss" onClick={() => setNotice('')}><X size={15}/></button></div>}
    <main>
      {section === 'home' && <>
        <section className="hero"><img src="/images/hero.png" alt={ar ? 'غرفة معيشة هادئة بخامات طبيعية وإضاءة دافئة' : 'Warm interior with sculptural table and olive chair'} /><div className="hero-shade"/><div className="hero-copy"><span className="eyebrow light">{t.heroEyebrow}</span><h1 dangerouslySetInnerHTML={{ __html: t.heroTitle }}/><p>{t.heroText}</p><a className="button light-button" href={`${base}/shop`}>{t.discover}{arrow}</a></div><span className="hero-index">01 / 03</span></section>
        <div className="promise-strip"><span>✳ {ar ? 'منتقى بعناية' : 'CURATED WITH CARE'}</span><span>✳ {ar ? 'صنع ليعيش معك' : 'MADE TO LIVE WITH'}</span><span>✳ {ar ? 'توصيل في كل الكويت' : 'DELIVERED ACROSS KUWAIT'}</span></div>
        <section className="section-shell signatures"><div className="section-heading"><div><span className="eyebrow">{t.signature}</span><h2>{t.favouritesTitle}</h2></div><a className="text-link" href={`${base}/shop`}>{t.viewAll} {arrow}</a></div><div className="product-grid">{(signatureProducts.length === 4 ? signatureProducts : products.slice(0, 4)).map(productCard)}</div></section>
        <section className="category-section"><div className="section-shell"><div className="section-heading"><div><span className="eyebrow">{t.categories}</span><h2>{t.categoriesTitle}</h2></div></div><div className="category-grid">{Object.entries(categoryNames).map(([key, value]) => <a className="category-tile" href={`${base}/shop?category=${key}`} key={key}><img src={categoryPictures[key]} alt="" loading="lazy"/><span>{value[ar ? 1 : 0]} {arrow}</span></a>)}</div><div className="collection-links"><span className="eyebrow">{ar ? 'المجموعات' : 'COLLECTIONS'}</span>{[['the-slow-room', ar ? 'الغرفة الهادئة' : 'The Slow Room'], ['after-the-sun', ar ? 'بعد الغروب' : 'After the Sun'], ['daily-rituals', ar ? 'طقوس يومية' : 'Daily Rituals']].map(([slug, label]) => <a key={slug} href={`${base}/shop?collection=${slug}`}>{label} {arrow}</a>)}</div></div></section>
        <section className="editorial section-shell"><div className="editorial-photo"><img src="https://images.unsplash.com/photo-1615874694520-474822394e73?w=1400&q=85" alt={ar ? 'تفاصيل منزلية دافئة' : 'A calm, tactile home interior'} loading="lazy"/></div><div className="editorial-copy"><span className="eyebrow">{t.ctaEyebrow}</span><h2>{t.ctaTitle}</h2><p>{t.ctaText}</p><a className="text-link" href={`${base}/story`}>{t.ctaButton} {arrow}</a></div></section>
      </>}
      {section === 'shop' && <section className="section-shell shop-page"><div className="page-intro"><span className="eyebrow">DARA / {t.shop.toUpperCase()}</span><h1>{t.shop}</h1><p>{ar ? 'قطع اختيرت لتجعل كل يوم أجمل.' : 'Thoughtfully chosen pieces for every corner of home.'}</p></div><div className="shop-toolbar"><div className="filter-tabs"><button className={category === 'all' ? 'active' : ''} onClick={() => setCategory('all')}>{t.all}</button>{Object.entries(categoryNames).map(([key, value]) => <button key={key} className={category === key ? 'active' : ''} onClick={() => setCategory(key)}>{value[ar ? 1 : 0]}</button>)}</div><div className="shop-tools"><label><Search size={17}/><input aria-label={t.search} placeholder={t.search} value={search} onChange={e => setSearch(e.target.value)}/></label><label><SlidersHorizontal size={16}/><select aria-label={t.sort} value={sort} onChange={e => setSort(e.target.value)}><option value="featured">{t.sort}</option><option value="price-asc">{t.priceLow}</option><option value="price-desc">{t.priceHigh}</option></select></label></div></div><div className="collection-filter"><span>{ar ? 'المجموعة' : 'Collection'}</span><select aria-label={ar ? 'المجموعة' : 'Collection'} value={collection} onChange={e => setCollection(e.target.value)}><option value="all">{ar ? 'كل المجموعات' : 'All collections'}</option><option value="the-slow-room">{ar ? 'الغرفة الهادئة' : 'The Slow Room'}</option><option value="after-the-sun">{ar ? 'بعد الغروب' : 'After the Sun'}</option><option value="daily-rituals">{ar ? 'طقوس يومية' : 'Daily Rituals'}</option></select></div>{!apiReady && <p className="preview-note">{t.preview}</p>}{loading ? <div className="loading-block">{t.loading}</div> : products.length ? <div className="product-grid shop-grid">{products.map(productCard)}</div> : empty(t.noResults, t.noResultsText)}</section>}
      {section === 'product' && <section className="section-shell detail-page">{loading ? <div className="loading-block">{t.loading}</div> : product ? <><div className="breadcrumbs"><a href={base}>{ar ? 'الرئيسية' : 'Home'}</a><span>/</span><a href={`${base}/shop`}>{t.shop}</a><span>/</span><span>{name(product)}</span></div><div className="detail-grid"><div className="detail-image"><img src={product.imageUrl} alt={name(product)}/></div><div className="detail-content"><span className="eyebrow">{categoryNames[product.category ?? 'decor']?.[ar ? 1 : 0]}</span><h1>{name(product)}</h1><p className="detail-price">{money(product.variants?.find(v => v.id === selectedVariant)?.priceFils ?? product.minPriceFils, locale)}</p><p className="detail-description">{ar ? product.descriptionAr : product.descriptionEn}</p>{product.variants && <><label className="field-label" htmlFor="variant">{ar ? 'الخيار' : 'Choose your finish & size'}</label><div className="select-wrap"><select id="variant" value={selectedVariant} onChange={e => setSelectedVariant(e.target.value)}>{product.variants.map(v => <option value={v.id} key={v.id} disabled={v.stock === 0}>{variantName(v)} {v.stock === 0 ? ` — ${ar ? 'نفد' : 'Sold out'}` : ''}</option>)}</select><ChevronDown size={18}/></div></>}<button className="button dark add-to-bag" onClick={addToCart} disabled={product.variants?.find(v => v.id === selectedVariant)?.stock === 0}>{t.add}<ShoppingBag size={19}/></button><button className="save-detail" onClick={() => toggleSaved(product.slug)}><Heart size={18} fill={saved.includes(product.slug) ? 'currentColor' : 'none'}/>{t.favorites}</button><div className="detail-accordions"><details open><summary>{t.details}</summary><p>{ar ? product.descriptionAr : product.descriptionEn}</p></details><details><summary>{ar ? 'التوصيل والإرجاع' : 'Delivery & returns'}</summary><p>{t.delivery}<br/>{t.returns}</p></details></div></div></div></> : empty(t.noResults, t.noResultsText)}</section>}
      {section === 'cart' && <section className="section-shell commerce-page"><div className="page-intro"><span className="eyebrow">DARA / {t.bag.toUpperCase()}</span><h1>{t.cartTitle}</h1></div>{cart.length ? <div className="commerce-grid"><div className="cart-lines">{cart.map(line => <article className="cart-line" key={line.variant.id}><img src={line.product.imageUrl} alt={name(line.product)}/><div><a href={`${base}/product/${line.product.slug}`}><h3>{name(line.product)}</h3></a><p>{variantName(line.variant)}</p><span>{money(line.variant.priceFils, locale)}</span><div className="quantity"><button aria-label="Decrease quantity" onClick={() => updateCart(line.quantity === 1 ? cart.filter(x => x.variant.id !== line.variant.id) : cart.map(x => x.variant.id === line.variant.id ? { ...x, quantity: x.quantity - 1 } : x))}><Minus size={15}/></button><span>{line.quantity}</span><button aria-label="Increase quantity" disabled={line.quantity >= line.variant.stock} onClick={() => updateCart(cart.map(x => x.variant.id === line.variant.id ? { ...x, quantity: x.quantity + 1 } : x))}><Plus size={15}/></button></div></div><button className="line-remove" onClick={() => updateCart(cart.filter(x => x.variant.id !== line.variant.id))} aria-label={`${t.remove} ${name(line.product)}`}><X size={18}/></button></article>)}</div><aside className="summary-card"><h2>{ar ? 'ملخص الطلب' : 'Order summary'}</h2><div><span>{t.subtotal}</span><strong>{money(quote?.subtotalFils ?? subtotal, locale)}</strong></div><div><span>{t.deliveryLabel}</span><strong>{quote ? (quote.deliveryFils ? money(quote.deliveryFils, locale) : t.free) : '—'}</strong></div><div className="summary-total"><span>{t.total}</span><strong>{money(quote?.totalFils ?? subtotal, locale)}</strong></div><a className="button dark full" href={`${base}/checkout`}>{t.checkout} {arrow}</a><p>{t.paymentNote}</p></aside></div> : empty(t.emptyCart, t.emptyCartText)}</section>}
      {section === 'checkout' && <section className="section-shell commerce-page"><div className="page-intro"><span className="eyebrow">DARA / CHECKOUT</span><h1>{t.checkoutTitle}</h1></div>{cart.length ? <div className="commerce-grid"><form className="checkout-form" onSubmit={submitOrder}><h2>{t.contact}</h2><div className="form-grid"><label>{t.fullName}<input required minLength={2} value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/></label><label>{t.email}<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })}/></label><label>{t.phone}<input required type="tel" minLength={7} value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })}/></label><label className="wide">{t.address}<textarea required minLength={10} rows={4} value={form.address} onChange={e => setForm({ ...form, address: e.target.value })}/></label></div><p className="simulation-banner">✳ {t.paymentNote}</p><button className="button dark" disabled={submitting}>{submitting ? t.loading : t.placeOrder} {arrow}</button></form><aside className="summary-card"><h2>{ar ? 'طلبك' : 'Your order'}</h2>{cart.map(line => <div className="checkout-line" key={line.variant.id}><span>{name(line.product)} × {line.quantity}</span><strong>{money(line.quantity * line.variant.priceFils, locale)}</strong></div>)}<label className="promo-label">{t.promo}<input value={promoCode} onChange={e => setPromoCode(e.target.value.toUpperCase())} placeholder="WELCOME10"/></label>{quote?.discountFils ? <div><span>{ar ? 'الخصم' : 'Discount'}</span><strong>−{money(quote.discountFils, locale)}</strong></div> : null}<div><span>{t.deliveryLabel}</span><strong>{quote ? quote.deliveryFils ? money(quote.deliveryFils, locale) : t.free : '—'}</strong></div><div className="summary-total"><span>{t.total}</span><strong>{money(quote?.totalFils ?? subtotal, locale)}</strong></div></aside></div> : empty(t.emptyCart, t.emptyCartText)}</section>}
      {section === 'order' && <section className="section-shell order-success"><div className="success-mark"><Check size={34}/></div><span className="eyebrow">DARA / ORDER</span><h1>{t.orderPlaced}</h1><p>{t.orderThanks}</p>{order?.order && <div className="order-box"><span>{t.orderNumber}</span><strong>{order.order.orderNumber}</strong><p>{t.paymentNote}</p><span>{ar ? 'الحالة' : 'Status'}: {order.order.status}</span></div>}<a className="button dark" href={`${base}/shop`}>{t.continue} {arrow}</a></section>}
      {section === 'favorites' && <section className="section-shell shop-page"><div className="page-intro"><span className="eyebrow">DARA / SAVED</span><h1>{t.savedTitle}</h1></div>{displayProducts.length ? <div className="product-grid shop-grid">{displayProducts.map(productCard)}</div> : empty(t.emptySaved, t.emptyCartText)}</section>}
      {section === 'story' && <section className="story-page"><div className="story-hero"><img src="/images/hero.png" alt=""/><div><span className="eyebrow light">DARA / دارا</span><h1>{ar ? 'لأن البيت إحساس.' : 'Home is a feeling.'}</h1></div></div><div className="story-copy"><span className="eyebrow">OUR STORY</span><h2>{ar ? 'قطع تحكي قصتك، كل يوم.' : 'Objects that become part of your story.'}</h2><p>{ar ? 'في دارا، نؤمن أن الأشياء التي نعيش معها تستحق أن تكون جميلة وعملية. نجمع قطعاً بخامات صادقة وأشكال هادئة، لترافق لحظات الحياة في الكويت.' : 'At Dara, we believe the objects we live with should be both beautiful and useful. We gather pieces with honest materials and quiet forms, made for the rhythm of life in Kuwait.'}</p><a className="button dark" href={`${base}/shop`}>{t.shop} {arrow}</a></div></section>}
      {section === 'account' && <section className="section-shell account-page"><div className="page-intro"><span className="eyebrow">DARA / ACCOUNT</span><h1>{t.account}</h1></div>{session?.user ? <div className="account-panel"><h2>{session.user.email}</h2><p>{ar ? 'مرحباً بعودتك.' : 'Welcome back.'}</p><h3>{t.myOrders}</h3>{orders.length ? orders.map(o => <a className="order-row" key={o.id} href={`${base}/order/${o.id}`}><span>{o.orderNumber}</span><span>{money(o.totalFils, locale)}</span><span>{o.status}</span>{arrow}</a>) : <p>{ar ? 'لا توجد طلبات بعد.' : 'No orders yet.'}</p>}<button className="text-link" onClick={() => mutate('/v1/auth/logout', 'POST').then(() => setSession({ user: null })).catch(() => {})}>{ar ? 'تسجيل الخروج' : 'Sign out'} {arrow}</button></div> : <div className="account-panel"><div className="auth-tabs"><button className={accountMode === 'login' ? 'active' : ''} onClick={() => setAccountMode('login')}>{t.signIn}</button><button className={accountMode === 'register' ? 'active' : ''} onClick={() => setAccountMode('register')}>{t.register}</button></div><form onSubmit={submitAuth}>{accountMode === 'register' && <label>{t.fullName}<input name="name" required minLength={2}/></label>}<label>{t.email}<input name="email" type="email" required/></label><label>{t.password}<input name="password" type="password" required minLength={accountMode === 'register' ? 12 : 1} value={password} onChange={e => setPassword(e.target.value)}/></label><button className="button dark" disabled={submitting}>{accountMode === 'login' ? t.signIn : t.register} {arrow}</button></form></div>}</section>}
    </main>
    <footer className="site-footer"><div className="section-shell footer-grid">{navFooter}</div><div className="footer-bottom section-shell"><span>© {new Date().getFullYear()} DARA. {ar ? 'صنع بحب في الكويت.' : 'Made for living in Kuwait.'}</span><span>KWD · {ar ? 'العربية' : 'ENGLISH'}</span></div></footer>
  </div>;
}
