import { pgTable, uuid, text, integer, boolean, timestamp, jsonb, uniqueIndex, index } from 'drizzle-orm/pg-core';

const id = () => uuid('id').primaryKey().defaultRandom();
const created = () => timestamp('created_at', { withTimezone: true }).notNull().defaultNow();
export const users = pgTable('users', { id: id(), email: text('email').notNull().unique(), name: text('name').notNull(), passwordHash: text('password_hash').notNull(), role: text('role').notNull().default('customer'), createdAt: created() });
export const sessions = pgTable('sessions', { id: id(), userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }), tokenHash: text('token_hash').notNull().unique(), csrfToken: text('csrf_token').notNull(), expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(), createdAt: created() });
export const categories = pgTable('categories', { id: id(), slug: text('slug').notNull().unique(), nameEn: text('name_en').notNull(), nameAr: text('name_ar').notNull() });
export const collections = pgTable('collections', { id: id(), slug: text('slug').notNull().unique(), nameEn: text('name_en').notNull(), nameAr: text('name_ar').notNull(), descriptionEn: text('description_en').notNull().default(''), descriptionAr: text('description_ar').notNull().default('') });
export const products = pgTable('products', { id: id(), slug: text('slug').notNull().unique(), nameEn: text('name_en').notNull(), nameAr: text('name_ar').notNull(), descriptionEn: text('description_en').notNull(), descriptionAr: text('description_ar').notNull(), categoryId: uuid('category_id').references(() => categories.id), collectionId: uuid('collection_id').references(() => collections.id), imageUrl: text('image_url').notNull(), featured: boolean('featured').notNull().default(false), active: boolean('active').notNull().default(true), createdAt: created() }, t => [index('products_category_idx').on(t.categoryId)]);
export const productImages = pgTable('product_images', { id: id(), productId: uuid('product_id').notNull().references(() => products.id, { onDelete: 'cascade' }), url: text('url').notNull(), altEn: text('alt_en').notNull(), altAr: text('alt_ar').notNull(), position: integer('position').notNull().default(0) });
export const variants = pgTable('variants', { id: id(), productId: uuid('product_id').notNull().references(() => products.id, { onDelete: 'cascade' }), sku: text('sku').notNull().unique(), labelEn: text('label_en').notNull(), labelAr: text('label_ar').notNull(), priceFils: integer('price_fils').notNull(), stock: integer('stock').notNull().default(0), active: boolean('active').notNull().default(true) }, t => [index('variants_product_idx').on(t.productId)]);
export const stockMovements = pgTable('stock_movements', { id: id(), variantId: uuid('variant_id').notNull().references(() => variants.id), delta: integer('delta').notNull(), reason: text('reason').notNull(), orderId: uuid('order_id'), actorId: uuid('actor_id'), createdAt: created() });
export const promotions = pgTable('promotions', { id: id(), code: text('code').notNull().unique(), percentOff: integer('percent_off').notNull(), active: boolean('active').notNull().default(true), startsAt: timestamp('starts_at', { withTimezone: true }), endsAt: timestamp('ends_at', { withTimezone: true }) });
export const orders = pgTable('orders', { id: id(), orderNumber: text('order_number').notNull().unique(), userId: uuid('user_id').references(() => users.id), email: text('email').notNull(), name: text('name').notNull(), phone: text('phone').notNull(), address: text('address').notNull(), trackingTokenHash: text('tracking_token_hash').notNull(), status: text('status').notNull().default('placed'), subtotalFils: integer('subtotal_fils').notNull(), discountFils: integer('discount_fils').notNull(), deliveryFils: integer('delivery_fils').notNull(), totalFils: integer('total_fils').notNull(), promotionCode: text('promotion_code'), idempotencyKey: uuid('idempotency_key').notNull().unique(), stockRestored: boolean('stock_restored').notNull().default(false), createdAt: created() }, t => [index('orders_email_idx').on(t.email)]);
export const orderItems = pgTable('order_items', { id: id(), orderId: uuid('order_id').notNull().references(() => orders.id), variantId: uuid('variant_id').notNull().references(() => variants.id), sku: text('sku').notNull(), nameEn: text('name_en').notNull(), nameAr: text('name_ar').notNull(), labelEn: text('label_en').notNull(), labelAr: text('label_ar').notNull(), quantity: integer('quantity').notNull(), unitPriceFils: integer('unit_price_fils').notNull() });
export const payments = pgTable('payments', { id: id(), orderId: uuid('order_id').notNull().references(() => orders.id), provider: text('provider').notNull().default('simulation'), status: text('status').notNull().default('simulated_paid'), amountFils: integer('amount_fils').notNull(), createdAt: created() });
export const auditEvents = pgTable('audit_events', { id: id(), actorId: uuid('actor_id').references(() => users.id), action: text('action').notNull(), subject: text('subject').notNull(), details: jsonb('details').notNull().default({}), createdAt: created() });
export const inventoryEvents = pgTable('inventory_events', { id: id(), variantId: uuid('variant_id').notNull().references(() => variants.id), stock: integer('stock').notNull(), createdAt: created() }, t => [index('inventory_events_created_idx').on(t.createdAt)]);
export const emailPreviews = pgTable('email_previews', { id: id(), to: text('recipient').notNull(), subject: text('subject').notNull(), html: text('html').notNull(), createdAt: created() });
